networks:
  custom_network:
    driver: bridge
volumes:
  postgres-data:
  postgres-logs:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    networks:
      - custom_network
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - custom_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}', '-d', '${DB_NAME}']
      interval: 1s
      timeout: 5s
      retries: 10
