networks:
  custom_network:
    driver: bridge
volumes:
  postgres-data:
  postgres-logs:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9229:9229'
      - '${APP_PORT}:${APP_PORT}'
    environment:
      DB_HOST: database
    # volumes:
    #   - /usr/src/node_modules
    #   - .:/usr/src/app
    develop:
      watch:
        - action: sync
          path: src
          target: /usr/src/app/src
        - action: sync
          path: prisma
          target: /usr/src/app/prisma
        - action: rebuild
          path: package.json
    networks:
      - custom_network
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    networks:
      - custom_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}', '-d', '${DB_NAME}']
      interval: 1s
      timeout: 5s
      retries: 10
